CREATE DATABASE Cofetarie
GO
USE Cofetarie
GO


CREATE TABLE Locatie (ID_Locatie INT PRIMARY KEY IDENTITY(500,1), Adresa VARCHAR(30) UNIQUE)

CREATE TABLE Ingredient (ID_Ingredient INT PRIMARY KEY IDENTITY(100,1), Denumire VARCHAR(30), Cantitate INT, Pret FLOAT, Expirare DATE DEFAULT '2023-12-25') 

CREATE TABLE Proprietar (CNP VARCHAR(15) PRIMARY KEY, Nume VARCHAR(30) NOT NULL, Adresa VARCHAR(30))

CREATE TABLE Angajat (CNP VARCHAR(15) PRIMARY KEY, Nume VARCHAR(30) NOT NULL, Functie VARCHAR(30) NOT NULL,
Salariu FLOAT DEFAULT 1500.0, Ore INT DEFAULT 8, CNP_Proprietar VARCHAR(15) FOREIGN KEY REFERENCES Proprietar(CNP))

CREATE TABLE Reteta (ID_Reteta INT PRIMARY KEY IDENTITY(200,1),Titlu VARCHAR(30), Timp INT, ModPreparare VARCHAR(30))

CREATE TABLE Client (Cod_Client INT PRIMARY KEY IDENTITY(1000,1), Nume VARCHAR(30) NOT NULL)

CREATE TABLE Recenzie (ID_Recenzie INT PRIMARY KEY IDENTITY(300,1), Nota INT CHECK (Nota>=1 AND Nota<=10),
Cod_Client INT FOREIGN KEY REFERENCES Client(Cod_Client))

CREATE TABLE Factura (Nr_Factura INT PRIMARY KEY IDENTITY(2000,1), Data DATE DEFAULT GETDATE(), Valoare INT,  Cod_Client INT FOREIGN KEY REFERENCES Client(Cod_Client))

CREATE TABLE Produs (ID_Produs INT PRIMARY KEY IDENTITY(400,1), Expirare DATE NOT NULL, Gramaj INT NOT NULL, Pret FLOAT NOT NULL,
Alergeni VARCHAR(50) DEFAULT NULL)

DROP TABLE Produs

CREATE TABLE Produs (ID_Produs INT PRIMARY KEY IDENTITY(400,1),Denumire VARCHAR(30), Expirare DATE NOT NULL, Gramaj INT NOT NULL, Pret FLOAT NOT NULL,
Alergeni VARCHAR(50) DEFAULT NULL, Cod_Client INT FOREIGN KEY REFERENCES Client(Cod_Client),
CNP_Angajat VARCHAR(15) FOREIGN KEY REFERENCES Angajat(CNP), ID_Locatie INT FOREIGN KEY REFERENCES Locatie(ID_Locatie))

CREATE TABLE ProdusIngredient (ID_Produs INT FOREIGN KEY REFERENCES Produs(ID_Produs), 
ID_Ingredient INT FOREIGN KEY REFERENCES Ingredient(ID_Ingredient),
CONSTRAINT pk_ProdusIngredient PRIMARY KEY (ID_Produs, ID_Ingredient))

CREATE TABLE RetetaIngredient (ID_Reteta INT FOREIGN KEY REFERENCES Reteta(ID_Reteta),
ID_Ingredient INT FOREIGN KEY REFERENCES Ingredient(ID_Ingredient),
CONSTRAINT pk_RetetaIngredient PRIMARY KEY (ID_Reteta, ID_Ingredient))

